"""add_invoice_attachment_fields

Revision ID: 467164d8d5af
Revises: 951a7ee5381c
Create Date: 2025-08-06 03:02:41.728106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '467164d8d5af'
down_revision: Union[str, Sequence[str], None] = '951a7ee5381c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    # If core master tables do not exist (fresh env), skip this migration gracefully
    if not ("master_users" in tables and "tenants" in tables):
        return

    # ### commands auto generated by Alembic - adjusted with safety checks ###
    op.drop_index('ix_page_views_id', table_name='page_views')
    op.drop_index('ix_page_views_path', table_name='page_views')
    op.drop_index('ix_page_views_tenant_id', table_name='page_views')
    op.drop_index('ix_page_views_timestamp', table_name='page_views')
    op.drop_index('ix_page_views_user_email', table_name='page_views')
    op.drop_table('page_views')
    op.alter_column('master_users', 'show_analytics',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('master_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('master_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_master_users_email', table_name='master_users')
    op.drop_index('idx_master_users_tenant_id', table_name='master_users')
    op.drop_constraint('master_users_email_key', 'master_users', type_='unique')
    op.create_index(op.f('ix_master_users_email'), 'master_users', ['email'], unique=True)
    op.create_index(op.f('ix_master_users_id'), 'master_users', ['id'], unique=False)
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenants', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_tenants_subdomain', table_name='tenants')
    op.drop_constraint('tenants_subdomain_key', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if not ("master_users" in tables and "tenants" in tables):
        return
    # ### commands auto generated by Alembic - adjusted with safety checks ###
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.create_unique_constraint('tenants_subdomain_key', 'tenants', ['subdomain'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_tenants_subdomain', 'tenants', ['subdomain'], unique=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenants', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tenants', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_master_users_id'), table_name='master_users')
    op.drop_index(op.f('ix_master_users_email'), table_name='master_users')
    op.create_unique_constraint('master_users_email_key', 'master_users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_master_users_tenant_id', 'master_users', ['tenant_id'], unique=False)
    op.create_index('idx_master_users_email', 'master_users', ['email'], unique=False)
    op.alter_column('master_users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('master_users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('master_users', 'show_analytics',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('page_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='page_views_pkey')
    )
    op.create_index('ix_page_views_user_email', 'page_views', ['user_email'], unique=False)
    op.create_index('ix_page_views_timestamp', 'page_views', ['timestamp'], unique=False)
    op.create_index('ix_page_views_tenant_id', 'page_views', ['tenant_id'], unique=False)
    op.create_index('ix_page_views_path', 'page_views', ['path'], unique=False)
    op.create_index('ix_page_views_id', 'page_views', ['id'], unique=False)
    # ### end Alembic commands ###
