{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ include "invoice-app.namespace" . }}
  labels:
    {{- include "invoice-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.api.env.SECRET_KEY | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.api.secrets.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.api.secrets.GOOGLE_CLIENT_SECRET | quote }}
  SLACK_VERIFICATION_TOKEN: {{ .Values.api.env.SLACK_VERIFICATION_TOKEN | quote }}
  SLACK_BOT_TOKEN: {{ .Values.api.env.SLACK_BOT_TOKEN | quote }}
  SLACK_CLIENT_ID: {{ .Values.api.env.SLACK_CLIENT_ID | quote }}
  SLACK_CLIENT_SECRET: {{ .Values.api.env.SLACK_CLIENT_SECRET | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.api.env.SLACK_SIGNING_SECRET | quote }}
{{- end }}