services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=sqlite:////app/invoice_app.db
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - app-network
    # Causes issue
    # volumes:
    #   - ./ui:/app

networks:
  app-network:
    driver: bridge 